/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.smeagol.magento.filetemplates.block;

import javax.swing.JPanel;

public final class BlockVisualPanel1 extends JPanel {

    /**
     * Creates new form BlockVisualPanel1
     */
    public BlockVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Step #1";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        lblClassText = new javax.swing.JLabel();
        lblExtends = new javax.swing.JLabel();
        txtExtends = new javax.swing.JTextField();
        lblModule = new javax.swing.JLabel();
        txtModule = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        cboxRewrite = new javax.swing.JCheckBox();

        txtName.setText(org.openide.util.NbBundle.getMessage(BlockVisualPanel1.class, "BlockVisualPanel1.txtName.text")); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblName, org.openide.util.NbBundle.getMessage(BlockVisualPanel1.class, "BlockVisualPanel1.lblName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblClass, org.openide.util.NbBundle.getMessage(BlockVisualPanel1.class, "BlockVisualPanel1.lblClass.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblClassText, org.openide.util.NbBundle.getMessage(BlockVisualPanel1.class, "BlockVisualPanel1.lblClassText.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblExtends, org.openide.util.NbBundle.getMessage(BlockVisualPanel1.class, "BlockVisualPanel1.lblExtends.text")); // NOI18N

        txtExtends.setText(org.openide.util.NbBundle.getMessage(BlockVisualPanel1.class, "BlockVisualPanel1.txtExtends.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblModule, org.openide.util.NbBundle.getMessage(BlockVisualPanel1.class, "BlockVisualPanel1.lblModule.text")); // NOI18N

        txtModule.setText(org.openide.util.NbBundle.getMessage(BlockVisualPanel1.class, "BlockVisualPanel1.txtModule.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnBrowse, org.openide.util.NbBundle.getMessage(BlockVisualPanel1.class, "BlockVisualPanel1.btnBrowse.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cboxRewrite, org.openide.util.NbBundle.getMessage(BlockVisualPanel1.class, "BlockVisualPanel1.cboxRewrite.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblExtends)
                        .addGap(6, 6, 6)
                        .addComponent(txtExtends, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModule)
                            .addComponent(lblName)
                            .addComponent(lblClass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtModule)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowse))
                            .addComponent(txtName)
                            .addComponent(lblClassText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxRewrite)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModule)
                    .addComponent(txtModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClass)
                    .addComponent(lblClassText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExtends)
                    .addComponent(txtExtends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxRewrite)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped

    }//GEN-LAST:event_txtNameKeyTyped

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        String pre = this.txtModule.getText() + "_";
        String post = "Controller";
        this.lblClassText.setText(pre + this.txtName.getText() + post);
    }//GEN-LAST:event_txtNameKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JCheckBox cboxRewrite;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblClassText;
    private javax.swing.JLabel lblExtends;
    private javax.swing.JLabel lblModule;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtExtends;
    private javax.swing.JTextField txtModule;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
