/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.smeagol.magento.filetemplates.controller;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import pl.smeagol.magento.filetemplates.utils.StringModifier;

public final class ControllerVisualPanel2 extends JPanel {

    /**
     * Creates new form ControllerVisualPanel2
     */
    public ControllerVisualPanel2() {
        initComponents();
        modelAction = new DefaultListModel();
        lstAction.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lstAction.setModel(modelAction);
    }

    @Override
    public String getName() {
        return "Define actions";
    }

    private void addActionToController() {
        String actionName = txtAction.getText();
        actionName = actionName.replaceAll("\\W", "");
        actionName = StringModifier.lcFirst(actionName);
        modelAction.addElement(actionName);
        lstAction.setModel(modelAction);
        txtAction.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuAction = new javax.swing.JPopupMenu();
        menuActionRemove = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAction = new javax.swing.JList();
        txtAction = new javax.swing.JTextField();
        lblAction = new javax.swing.JLabel();
        btnActionAdd = new javax.swing.JButton();
        cboxPostDispatch = new javax.swing.JCheckBox();
        cboxPreDispatch = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(menuActionRemove, org.openide.util.NbBundle.getMessage(ControllerVisualPanel2.class, "ControllerVisualPanel2.menuActionRemove.text")); // NOI18N
        menuActionRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionRemoveActionPerformed(evt);
            }
        });
        menuAction.add(menuActionRemove);

        lstAction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstActionMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(lstAction);

        txtAction.setText(org.openide.util.NbBundle.getMessage(ControllerVisualPanel2.class, "ControllerVisualPanel2.txtAction.text")); // NOI18N
        txtAction.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtActionKeyReleased(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblAction, org.openide.util.NbBundle.getMessage(ControllerVisualPanel2.class, "ControllerVisualPanel2.lblAction.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnActionAdd, org.openide.util.NbBundle.getMessage(ControllerVisualPanel2.class, "ControllerVisualPanel2.btnActionAdd.text")); // NOI18N
        btnActionAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionAddActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(cboxPostDispatch, org.openide.util.NbBundle.getMessage(ControllerVisualPanel2.class, "ControllerVisualPanel2.cboxPostDispatch.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cboxPreDispatch, org.openide.util.NbBundle.getMessage(ControllerVisualPanel2.class, "ControllerVisualPanel2.cboxPreDispatch.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActionAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxPostDispatch)
                            .addComponent(cboxPreDispatch))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAction)
                    .addComponent(btnActionAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxPreDispatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxPostDispatch)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionAddActionPerformed
        addActionToController();
        txtAction.requestFocus();
    }//GEN-LAST:event_btnActionAddActionPerformed

    private void txtActionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtActionKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addActionToController();
        }
    }//GEN-LAST:event_txtActionKeyReleased

    private void lstActionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstActionMouseReleased
        if (SwingUtilities.isRightMouseButton(evt)) {
            int index = lstAction.locationToIndex(evt.getPoint());
            if (index != -1) {
                lstAction.setSelectedIndex(index);
                menuAction.setLocation(evt.getLocationOnScreen());
                menuAction.setVisible(true);
            }
        }
    }//GEN-LAST:event_lstActionMouseReleased

    private void menuActionRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionRemoveActionPerformed
        modelAction.remove(lstAction.getSelectedIndex());
        menuAction.setVisible(false);
    }//GEN-LAST:event_menuActionRemoveActionPerformed
    private DefaultListModel modelAction;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActionAdd;
    private javax.swing.JCheckBox cboxPostDispatch;
    private javax.swing.JCheckBox cboxPreDispatch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAction;
    private javax.swing.JList lstAction;
    private javax.swing.JPopupMenu menuAction;
    private javax.swing.JMenuItem menuActionRemove;
    private javax.swing.JTextField txtAction;
    // End of variables declaration//GEN-END:variables
}
